### PR TITLE
Changed show page to show all relevant fields

### LINKED ISSUE #38: Configure Show Page

### LINKED ISSUE #87: Configure Admin panel to handle exceptions to what we want displayed on show page
Display the field unless it is part of the exceptions list.

### PR DESCRIPTION
**Pull request by straleyb**
This changes the implementation of the show page to show all fields that are attached to the document. It also implements a new object that filters out exceptions to what we want to display. The show page now displays all keys associated with said document that are not included within the exceptions list. Fixes #87, Fixes #38

### CODE REVIEW

**Comment by straleyb** [comment]
@terrellt @balesh2 check it out and tell me what you think.

File: app/models/solr_document.rb [hunk 1]
```diff
@@ -49,4 +53,10 @@ def file_distributor
     fd
   end
 
+  def key_filter
+    kf = BuildingOregon::KeyFilter.new(self.keys)
+    kf.exceptions= METADATA["Exceptions"]
```
Comment (terrellt) [inline app/models/solr_document.rb]: Why not pass this in initialization?

Comment (straleyb) [inline app/models/solr_document.rb]: Good question. Ill change that now. Easy peasy.

File: app/models/solr_document.rb [hunk 2]
```diff
@@ -64,4 +68,9 @@ def file_distributor
     fd
   end
 
+  def key_filter
+    kf = BuildingOregon::KeyFilter.new(self.keys, METADATA["Exceptions"])
```
Comment (terrellt) [inline app/models/solr_document.rb]: No reason to set a variable anymore.

File: app/views/catalog/_show_default.html.erb [hunk 3]
```diff
@@ -2,12 +2,14 @@
...
-    <% if should_render_show_field? document, field %>
-      <dt class="blacklight-<%= field_name.parameterize %>"><%= render_document_show_field_label document, field: field_name %></dt>
-      <dd class="blacklight-<%= field_name.parameterize %>">
-        <%= render_document_show_field_value document, field: field_name %>
-      </dd>
-    <% end -%>
+  <% document.filter_show_exceptions.each do |field_name| -%>
+    <dt class="blacklight-<%= field_name.parameterize %>"><%= render_document_show_field_label(document, field: field_name.gsub("desc_metadata__", "").gsub("ssm", "").gsub("ssim", "").gsub("label", "")) %></dt>
+    <dd class="blacklight-<%= field_name.parameterize %>">
+    <% if(render_document_show_field_value document, field: field_name).include?("$") %>
```
Comment (terrellt) [inline app/views/catalog/_show_default.html.erb]: Didn't we fix this with something like #94 before?

Comment (straleyb) [inline app/views/catalog/_show_default.html.erb]: So in #94, that is where I got the fields simply to display. They were still in the form blah$https://blah.com and thats what this PR fixed.

Comment (terrellt) [inline app/views/catalog/_show_default.html.erb]: Yeah - #83. Why the revert?

Comment (straleyb) [inline app/views/catalog/_show_default.html.erb]: err. I meant that vice versa.

Comment (terrellt) [inline app/views/catalog/_show_default.html.erb]: #83 should have taken care of the $.

Comment (straleyb) [inline app/views/catalog/_show_default.html.erb]: @terrellt Wow I got so confused for like 10 minutes. So I looked at it and the reason why I do this is because if a field does not contain a $, the view does not load. So I added this bit in to check to see if it is a normal field value or a field value with a $ in it.

**Comment by terrellt** [comment]
Needs rebased
