### PR TITLE
Feature/fix labels

### LINKED ISSUE #165: Make default list length 100

### LINKED ISSUE #167: Fix Show View Labels
http://building-oregon-dev.library.oregonstate.edu/catalog/oregondigital:df67rd52x

Also remove Coordinates_llsim and "Date Decades"

### LINKED ISSUE #169: Remove login links on full screen

### PR DESCRIPTION
**Pull request by straleyb**
Fixes #169, Fixes #165, Fixes #167. This fixes several things:
    *removes some useless fields from the show page, 
    *removes the login links completely from the nav-bar 
    *fixes some sizing issues with the logo on larger size screens
    *changes the default per page to 100
    *removes show config from catalog controller

I also refactored the show page to not use gsub within the view and gave that responsibility to a new object which sanitizes fields passed to it.

### CODE REVIEW

File: lib/building_oregon/field_sanitizer.rb [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+    private
+
+    def remove_metadata_tag
+      @field.gsub!("desc_metadata__", "")
+      remove_format
+    end
+
+    def remove_format
+      format_list.each {|format| @field.gsub!(format, "")}
+      @field
```
Comment (straleyb) [inline lib/building_oregon/field_sanitizer.rb]: I didn't really know where to put this, since I want the field to be returned instead of the format_list. I felt like I could have either put it into the sanitize field, or where it is currently? Any recommendations?

Comment (terrellt) [inline lib/building_oregon/field_sanitizer.rb]: I'd return it in #sanitize.

File: app/models/solr_document.rb [hunk 2]
```diff
@@ -48,6 +48,10 @@ def build_link(field)
       !value.to_s.start_with?("http")
     end
   end
+  
+  def sanitize_field(field)
+    field_sanitizer(field).sanitize
```
Comment (terrellt) [inline app/models/solr_document.rb]: Prefer binding to object interface rather than method interface. I'd do
```ruby
field_sanitizer.new(field).sanitize
```
